title: gitstua-course2
description: a simple course to demonstrate course creation
template:
  repo: gitstua-course2-template
  name: gitstua-course2
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
